# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad4a2e579db566b82a583e3da3662ee876a7eae449a0ec2b8d57d278474714d5780c2c6a4cc717d730dc2ddf824fef994462942c6867a4041982c6986a62f99f

test:
  secret_key_base: 04b66819ff3a09bbc47d24bb2eca20089f92bf71d7e24fe94b54839b7f47298da9b2072a1d8291bf9ecd00d24e491e7702c25dd7fa2039d9b51f54e74c8a45c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
